 services:
  jitsi-openid:
    image: mod242/jitsi-go-openid:latest
    restart: always
    environment:
      - 'JITSI_SECRET=xxxxx' # -> Must match jwt_secret from Jitsi
      - 'JITSI_URL=https://xxxxx' # -> Base URL of your Jitsi-Instance
      - 'JITSI_SUB=xxxx' # -> Must match JWT_APP_ID from Jitsi
      - 'ISSUER_BASE_URL=xxxx' # -> Base URL of OpenID Connect provider
      - 'BASE_URL=https://xxxx' # -> Public Base URL of this Application (should run behind Reverse Proxy)
      - 'CLIENT_ID=xxxxxxx' # -> ClientID from Oauth Provider
      - 'SECRET=xxxxx' # -> Client Secret from Oauth Provider
      - 'PREJOIN=false' # -> Wheter the Prejoin page should be displayed again after Authentication
    expose: 
    - 3001
    networks:
            meet.jitsi: # -> Your Jitsi Network (if run co-located and exposed via Jitsi-Web)
